name: Update Latest Blog Posts

on:
  schedule:
    - cron: '0 1/2 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repos readme with latest blog posts.
    runs-on: ubuntu-latest
    
    steps:
      uses: actions/checkout@v2
      
      uses:
