name: Latest podcasts workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest podcast posts from users anchor.fm account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in anchor posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "PODCAST-POST-LIST"
          feed_list: "https://anchor.fm/s/82f19dfc/podcast/rss"
          max_post_count: 5
          template: "<a href='$url'>$title</a> </br> "
          
